//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cxp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cxpEntities : DbContext
    {
        public cxpEntities()
            : base("name=cxpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<conceptoDePago> conceptoDePagoes { get; set; }
        public virtual DbSet<proveedore> proveedores { get; set; }
        public virtual DbSet<solicitudesCheque> solicitudesCheques { get; set; }
        public virtual DbSet<tiposPersona> tiposPersonas { get; set; }
        public virtual DbSet<transaccione> transacciones { get; set; }
    }
}
