//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cxp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudesCheque
    {
        public int id { get; set; }
        public int noSolicitud { get; set; }
        public int idProveedor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string concepto { get; set; }
    
        public virtual proveedore proveedore { get; set; }
    }
}
